export const COURSE_CATEGORIES = [
  "Saúde e Esportes",
  "Finanças e Investimentos",
  "Relacionamentos",
  "Negócios e Carreira",
  "Espiritualidade",
  "Sexualidade",
  "Entretenimento",
  "Culinária e Gastronomia",
  "Idiomas",
  "Direito",
  "Apps & Software",
  "Literatura",
  "Casa e Construção",
  "Desenvolvimento Pessoal",
  "Moda e Beleza",
  "Animais e Plantas",
  "Educacional",
  "Hobbies",
  "Design",
  "Internet",
  "Ecologia e Meio Ambiente",
  "Música e Artes",
  "Tecnologia da Informação",
  "Outros",
  "Empreendedorismo Digital",
] as const;

export const COURSE_LANGUAGES = [
  "Português",
  "Inglês",
  "Espanhol",
  "Francês",
  "Alemão",
  "Italiano",
  "Outro",
] as const;

export const COURSE_COUNTRIES = [
  "Brasil",
  "Portugal",
  "Estados Unidos",
  "Espanha",
  "México",
  "Argentina",
  "Colômbia",
  "Chile",
  "Outro",
] as const;
